services:
  wol:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wol
    command: ["serve"]
    network_mode: host
    volumes:
      - ./data:/root/.config/wol
      - ./certs:/certs:ro
    restart: unless-stopped
